In [2]:
import pandas as pd

Loading data from data.csv, it is generated with data-grab.ipynb

In [34]:
data = pd.read_csv('data.csv')

In [35]:
data

,Unnamed: 0,Job ID,Job Title,Position,Institution,City,Country,Deadline,Published
0,0,66241,PhD Position – Molecular Neuromedicine,Ph.D. Student,Forschungszentrum Jülich,Genova,Italy,6 February 2022,14 January 2022
1,1,66078,PhD student position in Neuroscience: Object r...,Ph.D. Student,Technische Universität München,Freising,Germany,31 July 2022,13 January 2022
2,2,66064,Ph.D. Student : Studying brain circuits involv...,Ph.D. Student,CNRS - Université de Paris,Paris,France,12 February 2022,12 January 2022
3,3,66048,PhD in Behavioral Neuroscience in Copenhagen,Ph.D. Student,University of Copenhagen,Copenhagen,Denmark,15 February 2022,12 January 2022
4,4,65914,PhD student in Experimental Neuroscience,Ph.D. Student,Istituto Italiano di Tecnologia,Rovereto,Italy,10 February 2022,11 January 2022
...,...,...,...,...,...,...,...,...,...
250,10,4435,Ph.D. Student in Essen/Germany,Ph.D. Student,University Duisburg-Essen,Essen,Germany,1 March 2021,11 February 2021
251,11,4374,Ph.D. Student in BORDEAUX/France,Ph.D. Student,CNRS - University of Bordeaux,Bordeaux,France,15 February 2021,11 February 2021
252,12,4370,Post-doctoral position in BORDEAUX/France,Ph.D. Student,CNRS - University of Bordeaux,Bordeaux,France,15 February 2021,10 February 2021
253,13,4361,Ph.D. Student in Magdeburg/Germany,Ph.D. Student,Leibniz-Institute for Neurobiology,Magdeburg,Germany,28 February 2021,10 February 2021
254,14,4334,PhD Student Synaptic Molecular Pathology in Co...,Ph.D. Student,Biomedical Research Institute Sant Pau,Barcelona,Spain,4 February 2021,9 February 2021

In [36]:
data = data.drop('Unnamed: 0',axis='columns')

In [37]:
countryAliases = {'The Netherlands': 'Netherlands'}

data["Country"].replace(countryAliases, inplace=True)

In [38]:
countries = data['Country']
countries.value_counts()

Germany           98
France            32
United Kingdom    23
Italy             14
Netherlands       12
Switzerland       11
Norway            10
Belgium           10
Canada            10
Austria            7
Israel             6
Spain              5
Sweden             5
Denmark            2
Ireland            2
Iceland            1
Russia             1
United States      1
Japan              1
Portugal           1
Greece             1
India              1
Morocco            1
Name: Country, dtype: int64